repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: trailing-whitespace
        # let flake8 deal with py => dont treat docstrings.
        exclude_types: ['html', 'python']
    -   id: check-added-large-files
    -   id: check-ast
    #-   id: check-json
    -   id: check-merge-conflict
    #-   id: check-xml
    #-   id: check-yaml
    -   id: debug-statements
    -   id: detect-aws-credentials
        args:
        - --allow-missing-credentials
    -   id: detect-private-key
    -   id: end-of-file-fixer
        exclude_types: ['html']
    #-   id: requirements-txt-fixer
    -   id: mixed-line-ending
        args: ['--fix=no']

-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
    #-   id: identity # for debugging pre-commits

# -   repo: https://github.com/flakehell/flakehell
#     rev: v.0.8.0
# Until this gets merged: https://github.com/flakehell/flakehell/pull/20
-   repo: https://github.com/KPLauritzen/flakehell
    rev: d644612
    hooks:
    -   id: flakehell
        additional_dependencies: [
          flake8-docstrings,
          flake8-bugbear,
          flake8-comprehensions,
          flake8-isort,
          flake8-builtins,
          pep8-naming,
        ]

-   repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
    -   id: isort
