# Inspired by https://github.com/python-poetry/poetry/issues/366
# More elaborate (but is there a point to that?) tox/travis:
# https://github.com/python-poetry/poetry/issues/366#issuecomment-634666677

# Build matrix. Its "expansion" (outer prod) defines the default stage
language: python
dist: xenial
python:
  - 3.9
  - 3.8
  - 3.7 # `poetry install` sometimes fails on 3.7
before_install:
  # Get poetry
  - python --version
  - pip install -U pip
  - pip install poetry
  - travis_retry poetry install
  - pip install tox-travis # only use current/travis python!
install: skip # overwrite default (looks for requirements file)
before_script: skip
script: tox -- -rsx
after_script: skip

stages:
  - lint
  - test
  - coverage
  - deploy

# Explicitly included (i.e. particular) jobs (1 per dash).
# If the stage of a job is not def'd, the above stage is used,
# the default being the "test" stage. The 1st value of a
# matrix dimension (e.g. "python") is used, unless overwritten.
jobs:
  include:
    - stage: lint
      script: poetry run pre-commit run -a

    # Needed coz (ref dev_guide.py), coverage via tox tests will yield 0%.
    - stage: coverage
      install: pip install coveralls
      script: poetry run pytest
      after_success: coveralls || echo "failed"

    - stage: deploy
      script: skip
      before_deploy:
        - poetry build
      deploy:
        provider: pypi
        username: __token__
        password:
          secure: qUubHfUoTsaNXp0eb7IdFvikQkyNzhxx3QAQQBgOnSDcYB8t8MWOb2OYnZ1ZCdhrBP2JkMaf+wPxSqroDyOCgrBxsB2CFvlWhyuqfvU/E5YK+hiCJPri+N8UBrM+8UFkuHWQCJn+8wcshtmNZx2gGLTlVMBFTuSCvrMY86XbfcGNq4b78mPFq9F0qTqs5vlUfxVGRYfskeYmo1ZjF1Su3E0q298DJ/aSagKV/t4OgTsCfAUOgPEtdX7/3haO4vuUwJ0xgZO6ijzYv7exRCoxIkQr5fwnfamudLgtFrcVZoIe5SxdrPNs5iKoxx0h4wjxxq7EHrBqtp1mBQpU4uu8mrYRb5atulgcUljksvj8zOz8D3MJIqFVx3RZGI1cxw3WLXi877mMm5UWQxjynrRz85nOpYkvJ7Sbg07XCW8/1imlQ0/fU3s0g8CDucDrSYcgZTyMvPCGmFHTSeL1QH52drYKgCjB5OYfuijYfZBuBs8Yh0WpRhyE0gTikBTUNI/7QzkK7mflSA5dl3YiGUCprWChb8/KP1RjWE6x9DPhAZVNcVr4M5FVAdOFt5SR6iQX8VOmV1/hrdVHe4py4yjhKBd4Pd9b51gp/j93MvDQeKiJ9D1r8AQb+Onwd3iukewr9+Rxix8PuTTVNdAxidStNwTnA9MAFn4v3DpeHzeHWvQ=
        distributions: "sdist bdist_wheel"
        skip_cleanup: true
        on:
          #all_branches: false
          #condition: $TRAVIS_BUILD_STAGE_NAME = Deploy
          repo: patricknraanes/mpl-tools
          tags: true
      #if: tag IS present

# Dont cache .tox, ref: https://github.com/sclorg/rpm-list-builder/issues/28
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"
