# Inspired by https://github.com/python-poetry/poetry/issues/366
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
dist: xenial

stages:
  - lint
  - test
  - coverage
  # TODO:
  #- name: deploy
  #  if: tag IS present

# Might not be a good idea to cache .tox, ref:
# https://github.com/sclorg/rpm-list-builder/issues/28
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

jobs:
  fast_finish: true

  include:

    - stage: lint
      python: 3.9
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files

    # AFAIK, the main reason to use tox on travis-ci (as well as locally)
    # is just to avoid repeating ourselves.
    #
    # The package tox-travis ensures that only the environments matching
    # the *python version of the travis server* are run.
    #
    # If you want to only run specific [testenv:name] tests
    # (for example, heavier linting could be run through tox)
    # with specific stages/pythons, then see this examle:
    # https://github.com/python-poetry/poetry/issues/366#issuecomment-634666677
    - stage: test
      install: pip install tox-travis
      script: tox

    - stage: coverage
      python: 3.9
      install:
        - pip install --upgrade pip
        - pip install poetry coveralls
        - poetry install -v
      #before_script:
      script:
        - pytest
      after_success: coveralls || echo "failed"
      #after_script:
