# Inspired by https://github.com/python-poetry/poetry/issues/366
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
dist: xenial

# Overwrite default, which looks for requirements.txt, ref
# https://stackoverflow.com/a/57271598/38281
install: skip
script: skip

# https://stackoverflow.com/q/34377017/38281
#before_script:
#after_script:

# https://docs.travis-ci.com/user/build-stages/#what-are-build-stages
stages:
  - lint
  - test
  - test_with_make
  - coverage
  # TODO:
  #- name: deploy
  #  if: tag IS present

# Might not be a good idea to cache .tox, ref:
# https://github.com/sclorg/rpm-list-builder/issues/28
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"


jobs:
  fast_finish: true

  include:

    - stage: lint
      python: 3.9
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files

    # More elaborate (but is there a point to that?) tox/travis:
    # https://github.com/python-poetry/poetry/issues/366#issuecomment-634666677
    - stage: test
      install: pip install tox-travis # only use current (travis) python
      script: tox

    - stage: test_with_make
      install: make install
      script: make tox

    - stage: coverage
      python: 3.9
      install:
        - pip install --upgrade pip
        - pip install poetry coveralls
        - poetry install -v
      script:
        - pytest
      after_success: coveralls || echo "failed"
