# Inspired by https://github.com/python-poetry/poetry/issues/366
# More elaborate (but is there a point to that?) tox/travis:
# https://github.com/python-poetry/poetry/issues/366#issuecomment-634666677

language: python
python:
  - 3.9 # top => base version
  - 3.8
  - 3.7
dist: xenial

# https://stackoverflow.com/q/34377017/38281
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install poetry
  - poetry install -v
  # Only use current (travis) python (should install with poetry add?):
  - pip install tox-travis
before_script: skip
script: tox
after_script: skip

# Jobs run in parallel. But some things should only run
# after others have succeeded (eg. "deploy") => Stages
# Here we specify their order. Jobs (each dash under jobs.include)
# inherit previous stage name (the default being "test").
# https://docs.travis-ci.com/user/build-stages/#what-are-build-stages
stages:
  - lint
  - test
  - test_with_make
  - coverage
  # TODO:
  #- name: deploy
  #  if: tag IS present

# Might not be a good idea to cache .tox, ref:
# https://github.com/sclorg/rpm-list-builder/issues/28
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

jobs:
  # Don't wait for allowed-failures to declare build success.
  fast_finish: true

  include:

    - stage: lint
      python: 3.9
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files

    - stage: test_with_make
      python: 3.9
      install: make install
      script: make tox

    - stage: coverage
      python: 3.9
      install:
        - pip install poetry coveralls
        - poetry install -v
      script:
        - pytest
      after_success: coveralls || echo "failed"
