# Inspired by https://github.com/python-poetry/poetry/issues/366
# More elaborate (but is there a point to that?) tox/travis:
# https://github.com/python-poetry/poetry/issues/366#issuecomment-634666677

# Build matrix (used by "test") stage
language: python
dist: xenial
python:
  - 3.9
  - 3.8
  - 3.7
# https://stackoverflow.com/q/34377017/38281
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install poetry
  - poetry install -v
  - pip install tox-travis # only use current/travis python!
before_script: skip
script: tox
after_script: skip

# Jobs run in parallel. But some things should only run
# after others have succeeded (eg. "deploy") => Stages
# Here we specify their order.
# https://docs.travis-ci.com/user/build-stages/#what-are-build-stages
stages:
  - lint
  - test
  - test_with_make
  - coverage
  # TODO:
  #- name: deploy
  #  if: tag IS present

# Might not be a good idea to cache .tox, ref:
# https://github.com/sclorg/rpm-list-builder/issues/28
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

# Explicitly included (i.e. particular) jobs.
# There is one for each dash under `jobs.include`.
# The 1st value of a matrix dimension (e.g. "python") is used unless overwritten.
jobs:
  include:
    - stage: lint
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files

    - stage: test_with_make
      install: make install
      script: make tox

    - stage: coverage
      install:
        - pip install poetry coveralls
        - poetry install -v
      script:
        - pytest
      after_success: coveralls || echo "failed"
