# Inspired by https://github.com/python-poetry/poetry/issues/366
# More elaborate (but is there a point to that?) tox/travis:
# https://github.com/python-poetry/poetry/issues/366#issuecomment-634666677

# Build matrix. Its "expansion" (outer prod) defines the default stage
language: python
dist: xenial
python:
  - 3.9
  - 3.8
  - 3.7 # `poetry install` sometimes fails on 3.7
before_install:
  # Get poetry
  - python --version
  - pip install -U pip
  - pip install poetry
  - travis_retry poetry install
  - pip install tox-travis # only use current/travis python!
install: skip # overwrite default (looks for requirements file)
before_script: skip
script: tox -- -rsx
after_script: skip

stages:
  - lint
  - test
  - test_with_make
  - coverage
  - deploy

# Might not be a good idea to cache .tox, ref:
# https://github.com/sclorg/rpm-list-builder/issues/28
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

# Explicitly included (i.e. particular) jobs (1 per dash).
# If the stage of a job is not def'd, the above stage is used,
# the default being the "test" stage. The 1st value of a
# matrix dimension (e.g. "python") is used, unless overwritten.
jobs:
  include:
    - stage: lint
      script: poetry run pre-commit run --all-files

    # Needed coz (ref dev_guide.py), coverage via tox tests will yield 0%.
    - stage: coverage
      install: pip install coveralls
      script: poetry run pytest
      after_success: coveralls || echo "failed"

    - stage: deploy
      script:
        - echo Deploying to PyPI...
      before_deploy:
        # Username set as env var through web interface of project on travis
        - poetry config http-basic.pypi patricknraanes $PYPI_PASS
        #- poetry config pypi-token.pypi $PYPI_PASSWORD
        - poetry build
      deploy:
        provider: script
        script: poetry publish
        skip_cleanup: true
        on:
          #all_branches: false
          #condition: $TRAVIS_BUILD_STAGE_NAME = Deploy
          repo: patricknraanes/mpl-tools
          tags: true
      #if: tag IS present
